server:
  port: 8001

spring:
  application:
    name: uav-platform
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
##    driver-class-name: org.gjt.mm.mysql.Driver        #mysql驱动包
#    driver-class-name: com.mysql.cj.jdbc.Driver       #mysql驱动包
#    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding-utr-8&useSSL=false
#    username: root
#    password: 123456
  redis:
    host: localhost
    port: 6379
    database: 0
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.myyspringcloud.entities #所有Entity别名类所在包